{% set version = "0.2.5" %}

package:
  name: pyvirtualdisplay
  version: {{ version }}

source:
  fn: pyvirtualdisplay-{{ version }}.tar.gz
  url:  https://github.com/ponty/PyVirtualDisplay/archive/{{ version}}.tar.gz
  sha256: 30c13528871d032aec9c09b3a84452cb1d4f0dfc00a8f981df8bfa011b96e073

build:
  skip: true  # [win]
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - easyprocess

test:
  imports:
    - pyvirtualdisplay

about:
  home: https://github.com/ponty/pyvirtualdisplay
  license: BSD 2-clause
  license_file: LICENSE.txt
  summary: 'python wrapper for Xvfb, Xephyr and Xvnc'

extra:
  recipe-maintainers:
    - ReimarBauer
