{% set name = "pyvirtualdisplay" %}
{% set version = "2.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/PyVirtualDisplay-{{ version }}.tar.gz
  sha256: 3ecda6b183b03ba65dcfdf0019809722480d7b7e10eea6e3a40bf1ba3146bab7

build:
  number: 1
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - python >=3.6
  run:
    - easyprocess
    - python >=3.6
    - pillow

test:
  imports:
    - pyvirtualdisplay
    - pyvirtualdisplay.examples
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ponty/pyvirtualdisplay
  license: BSD-2-Clause
  license_file: LICENSE.txt
  summary: python wrapper for Xvfb, Xephyr and Xvnc

extra:
  recipe-maintainers:
    - ReimarBauer
