{% set version = "2.1" %}

package:
  name: pyvirtualdisplay
  version: {{ version }}

source:
  fn: pyvirtualdisplay-{{ version }}.tar.gz
  url: https://github.com/ponty/PyVirtualDisplay/archive/{{ version }}.tar.gz
  sha256: 95c15b1fc400984a6729ad412e17eebc36a66d60fb8cf8dca75cc9fe87c3a012

build:
  skip: true  # [win]
  number: 1
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - easyprocess
    - pillow

test:
  imports:
    - pyvirtualdisplay

about:
  home: https://github.com/ponty/pyvirtualdisplay
  license: BSD 2-clause
  license_file: LICENSE.txt
  summary: python wrapper for Xvfb, Xephyr and Xvnc

extra:
  recipe-maintainers:
    - ReimarBauer
