travis:
  secure:
    BINSTAR_TOKEN: Mh2XqTejhFBdJCRz8vTMrXLOoULsqtaif4AD/n9jH6bdR893ir8TuzaMrUHruJTadUOiBT9JGTzRLihKy97/FIfIHCHjMEEm5dArIRp+Wop9264OYYijj931Nyev1uNMXUYOE4E4DQ6uB+L6F5n3dDOoGE/z31zCCT9ZIxs9w/4n0Bwde/SX6uT3Id1h91bhIAw7eMK8pH9chUuA+L75bROHqycx80zvuD3UX1maEvfex3C8iEWbJjZXT05vWMc1bp5A2HhE1Q9iuEtaCf3X5e/tm4JnZPyc7SsXAMM7iGmnDW2jkaP2k5EjYuS87Slx/C9kRESAZ+zGnzmcWKBu9+BDRaROrVHyTau83zjm2OXl3lMjj2OEQHXhO/XKGipG0R7rklo4e5w/c7gVDzJeyhQ6qCh2rL80dLU2AvNESxqbX9ENh8q+wd1MiuTCRHxDjWaNq4BWKySvTAa13mXjF8vY+gxbhjW7GZMoPvcqtuoMu299KBj9X2wAkg7yfS/gX/ZDzNFT433uQ5i37uWb3Jwon3iwOLqQ2qhm1nnfuK8NxZb+A7Z5BJir85EbFdyL7+5uZImO1jDG75xOdAiyi69lNFyyW+V7V4OmAYfWcOQujr3CwAwual9/orGh0cV0yVNUsq6OMYVZN0K5fGnC/Z/tSgDLB2UKd8hQ3HAR8r0=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
