travis:
  secure:
    BINSTAR_TOKEN: PC6JYrvMWUb3ahNADFOE7vXVSIR/T+axAhrofKZaZYMj/XDrD47O452tQdcXZfBKiaBPSogC5KXlomAy93+JBQhx1HFZsdrgThryYk0+AVId4pPd5xPh4JoYW/xOdDQ5aNlf6kCfE8JP7DVxllNhNnyWaBESWbJujy3cZ6xt+JnCx5TX8a+PcjzduPt6hVcVMhPwp0se6bIxO+Yi/13sxoUfYmKdsV+PO5kXTdwoGWDa8eCKUpB0P1d4tNs918hIyGqex3qpwsB6hbFZKMCHgOFsyAL5l+m+zAlmqsvTtGAwODG3GJ4YwX4RjOkNrDl0qShWi1NNvHU+z76DJcuKp0CgRJZnAWbAdna3DcWqsnVPVX64evzzEoM2OKuWbL3Ra0W1GnnKDbi3BX9iZ9ZT10YcZn5i8RvFXq2t9lDSXlXRflBfBZHXH5C3brBs9ZmCE6gSArEH3AJuWxlbiA1gM5k3/+NYS5krmbJ34/TYPhuiW+8PpkUw4OHgVtLdNQ7gew/IlteSwR4fWKXtowk9rOp9svo2fSeQx5P6X9dU3nCwMPaR4BwvMeZV3Y6nXyDz7mAOE4Ood9ml6BFC4ZcUa4TeOpGvZQ0n5Z5Bgyw5LQzgbhemmUf8NaL3MowHHonbsnWCOAYzO8xNrJr6Xpcz/jd61/KNkn5m0c7WkpUFeUk=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
